## NumPy Exercises
##### Hope you've brushed up your NumPy knowledge. Now let's test it!

### Import NumPy

In [ ]:
import numpy as np

### Create an Array of 5 zeroes

In [ ]:
a=np.zeros(5, dtype= int)

### Create an Array of 10 ones

In [ ]:
b=np.ones(10, dtype= int)

### Create an Array of 20 sevens

In [ ]:
c=np.ones(20, dtype= int)*7

 ### Create an Array of integers from 2020 to 2050 (both inclusive)



```
b=np.arange(2020,2050+1)
```



### Create an Array of all ODD integers between 1 and 11 (both inclusive)

In [ ]:
b=np.arange(1,11+1,2)

# Create a 3x3 Matrix with nos. ranging from 1 to 10

In [ ]:
x=np.arange(1,10).reshape(3,3)

### Create a 2x2 Identity Matrix

In [ ]:
x=np.identity(2, dtype=int)

### Generate a random number between 0 and 1 using NumPy functions

In [ ]:
x=np.random.rand()


### Generate an array of 10 Random Numbers sampled from a standard normal distribution

##### You can revise statistics by clicking here:  <a href="https://www.mathsisfun.com/data/standard-normal-distribution.html"> <button type="button">Statistics</button></a>

In [ ]:
x=np.random.normal(0,1,10)

### Generate the following Matrix:

In [ ]:
x=np.arange(0.01,1.01,0.01).reshape(10,10)


## NumPy Indexing & Selection

### You have to produce the foll. matrix and replicate the outputs that follow:

- WRITE THE CODE THAT REPRODUCES THE OUTPUT OF THE CELLS THAT FOLLOW
- BE CAREFUL NOT TO RUN THE CELL THAT HAS THE OUTPUT
- OTHERWISE YOU WON'T BE ABLE TO SEE THE OUTPUT ANY MORE
- CODE IN THE CELLS PROVIDED IMMEDIATELY BELOW THE OUTPUT
- MAKE SURE THAT YOU DON'T REMOVE YOUR CODE ONCE THE DESIRED OUTPUT IS PRODUCED

### 1.


In [ ]:
x=np.arange(1,26).reshape(5,5)
print("array(",x,")")


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### 2.

In [ ]:
print("array("x[2:,1:],")")

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

### 3.

In [ ]:
print("array("x[3,4],")")


20

### 4.

In [ ]:
x[0:3,1].reshape((3,1))



array([[ 2],
       [ 7],
       [12]])

### 5.

In [ ]:
x[4,]


array([21, 22, 23, 24, 25])

### 6.  Find the average of all integer values in the matrix generated in 1.

In [ ]:
a=np.average(x)


### 7. Find the sum of all values in each row of the matrix generated in 1.

##### (Hint: Think in terms of axis!)

- Output should be: array( [15, 40, 65, 90, 115] )

In [ ]:
s=np.sum(x,1)


# Great Job!

### If you're still not confident about NumPy, revise it here: <a href="https://www.tutorialspoint.com/numpy/index.htm"> <button type="button">NumPy</button></a>